Correct import error in __init__.py
The following traceback error was seen:

Traceback (most recent call last):
  File "/app/app/initial_data.py", line 3, in <module>
    from app.db.init_db import init_db
  File "/app/app/db/init_db.py", line 1, in <module>
    from app.crud import user
  File "/app/app/crud/__init__.py", line 1, in <module>
    import item, user  # noqa: F401
ModuleNotFoundError: No module named 'item'

This commit will restore the import statement to the previous format,
but put each import on its own line.

Also see commit 0e663cca in cookiecutter:
https://github.com/br3ndonland/full-stack-fastapi-postgresql