Correct import error in init_db.py
The following traceback error was seen:

Traceback (most recent call last):
File "/app/app/initial_data.py", line 21, in <module>
main()
File "/app/app/initial_data.py", line 16, in main
init()
File "/app/app/initial_data.py", line 11, in init
init_db(db_session)
File "/app/app/db/init_db.py", line 17, in init_db
user = crud.user.get_by_email(db_session, email=config.FIRST_SUPERUSER)
AttributeError: module 'app.crud' has no attribute 'user'

This commit will correct the import of the user module.

Also see commit 764ffd8b in cookiecutter:
https://github.com/br3ndonland/full-stack-fastapi-postgresql